<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email' => '',
    'Full name' => '',
    'Password' => '',
    'Sign up' => '',
    'Spaces and special characters are not allowed.' => '',
    'Thank you for registration. Please check your inbox for verification email.' => '',
    'The username can only contain letters from A to Z, numbers from 0 to 9, a dot (.) in the middle, and the underscore \'_\'.' => '',
    'This email address has already been taken.' => '',
    'This username has already been taken.' => '',
    'Username' => '',
];
