<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email' => 'Email',
    'Password' => 'Parola',
    'Signup' => 'Inregistreaza-te',
    'Thank you for registration. Please check your inbox for verification email.' => 'Vă mulțumim pentru înregistrare. Verificați-vă căsuța de e-mail pentru e-mailul de verificare.',
    'This email address has already been taken.' => 'Această adresă de e-mail a fost deja luată.',
    'This username has already been taken.' => 'Acest nume de utilizator a fost deja luat.',
    'Username' => 'Username',
];
