<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Don\'t have an user account yet? {linkStart}Sign up here{linkEnd}' => 'Nu ai cont? {linkStart}Inscrie-te aici{linkEnd}',
    'If you forgot your password you can {linkStart}reset it{linkEnd}' => 'Daca ai uitat parola poti sa o {linkStart}resetezi{linkEnd}',
    'Incorrect username or password.' => 'Userul sau parola este gresit.',
    'Log in' => 'Log in',
    'Need new verification email? {linkStart}Resend{linkEnd}' => 'Ai nevoie de un email de verificare nou? {linkStart}Trimite din nou{linkEnd}',
    'Password' => 'Parola',
    'Remember me' => 'Tine-ma minte',
    'Username or email' => 'User sau email',
];
