<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email' => 'Email',
    'Password' => 'Parola',
    'Sign up' => 'Inscrie-te',
    'Thank you for registration. Please check your inbox for verification email.' => 'Iti mulțumim pentru înregistrare. Verifică-ți căsuța de e-mail pentru e-mailul de verificare.',
    'The username can only contain letters from A to Z, numbers from 0 to 9 and the underscore \'_\'.' => 'Username-ul poate contine doar litere de la A la Z, numere de la 0 la 9 si liniuta de jos \'_\'.',
    'This email address has already been taken.' => 'Această adresă de e-mail a fost deja luată.',
    'This username has already been taken.' => 'Acest nume de utilizator a fost deja luat.',
    'Username' => 'Username',
    'Full name' => 'Nume complet',
    'Spaces and special characters are not allowed.' => 'Spațiile și caracterele speciale nu sunt permise.',
];
