<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Check your email for further instructions.' => 'Verifică-ți e-mailul pentru instrucțiuni suplimentare.',
    'Email' => 'Email',
    'Resend verification email' => 'Retrimite email-ul de verificare',
    'Send' => 'Trimite',
    'Sorry, we are unable to resend verification email for the provided email address.' => 'Ne pare rău, nu putem retrimite e-mailul de verificare pentru adresa de e-mail furnizată.',
    'There is no user with this email address.' => 'Nu există niciun utilizator cu această adresă de e-mail.',
];
